export const state = {
    currentUser: null,
    conditionList: [],
    participantConditionList: [],
    participants: [],
    participantPage: 1,
    participantSortKey: 'createdAt',
    participantSortDirection: 'desc',
    contents: [],
    contentPage: 1,
    contentSortKey: 'participatedAt',
    contentSortDirection: 'desc',
    contentSearchQuery: '',
    contentDateFrom: '',
    contentDateTo: '',
    participantSearchQuery: '',
    scenarios: [],
    scenarioPage: 1,
    scenarioSortKey: 'createdAt',
    scenarioSortDirection: 'desc',
    scenarioSearchQuery: '',
    scenarioMissions: [],
    editingParticipantId: null,
    editingScenarioId: null,
    editingMissionIndex: null,
    testRecords: []
};
